version: '3'

services:
  web:
    image: nginx:1.13
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/code/public
    ports:
      - 8000:80
    links:
      - backend

  backend:
    image: joerx/expensely:devel
    build: ./
    volumes:
      - ./:/code
    links:
      - postgres
    environment:
      NODE_ENV: development
      PG_URL: tcp://expensely_usr:expensely_pw@postgres/expensely_dev
      PORT: 3000
    command: npm run backend:dev

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: expensely_pw
      POSTGRES_USER: expensely_usr
      POSTGRES_DB: expensely_dev
